#!/usr/bin/ruby

require 'json'
require 'uri'
require 'net/http'
require 'openssl'
require 'date'

require 'optparse'

APP_ID = APP_NAME = 'fbx_scripts'.freeze

options = {
  all: false,
  max_size: nil,
}
OptionParser.new do |o|
  o.banner = 'Usage: fbx_call_log [options] [MAX_SIZE]'

  o.on('-r', '--regex REGEX', Regexp, 'Filter calls (and total aggregate) via the NAME column') do |re|
    options[:regex] = re
  end

  o.on('-n', '--negate-regex REGEX', Regexp, 'Exclude calls (and total aggregate) via the NAME column') do |re|
    options[:neregex] = re
  end

  o.on('-a', '--all', 'Filter all calls (default is today)') do
    options[:all] = true
  end

  o.on('-m', '--max-size SIZE', Integer, 'Limit list by X count') do |max|
    options[:max_size] = max
  end
end.parse!

HOST = '192.168.1.254'.freeze

# http://stackoverflow.com/questions/4136248/how-to-generate-a-human-readable-time-range-using-ruby-on-rails
def humanize(secs)
  translations = [[60, :s], [60, :m], [24, :h], [1000, :d]]
  translations.map do |count, name|
    if secs > 0
      secs, n = secs.divmod(count)
      sprintf("%02d%s", n, name)
    end
  end.compact.reverse.join(' ')
end

def pretty_print_number(number)
  return number if number.length != 10

  number.reverse.scan(/../).join('.').reverse
end

def get_uri(path)
  URI.parse("https://#{HOST}" + path)
end

def env_file
  File.expand_path('~/.env/freebox')
end

def read_env_lines
  File.exist?(env_file) || raise("Create #{env_file}")
  File.readlines(env_file)
end

def env_lines
  @env_lines ||= read_env_lines
end

def load_env(name)
  found = env_lines.find { |l| l.start_with?(name) }
  return if found.nil?

  found.split('=').last.chomp
end

def post_json(uri)
  Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')
end

def request_auth(http)
  req = post_json(
    get_uri('/api/v4/login/authorize/')
  )

  req.body = JSON(
    app_id: APP_NAME,
    app_name: APP_NAME,
    app_version: '0.0.1',
    device_name: Socket.gethostname
  )
  res = http.request(req)
  j = JSON.parse(res.body)

  j.fetch('success') || fail('Request auth failed!')

  result = j.fetch('result')
  track_id = result.fetch('track_id')
  app_token = result.fetch('app_token')

  puts "Update env file: #{env_file}, with tokens below"
  puts "TRACK_ID=#{track_id}"
  puts "APP_TOKEN=#{app_token}"
  exit(1)
end

def auth_track(http, track)
  req = http.get(
    get_uri("/api/v4/login/authorize/#{track}")
  )

  res = JSON.parse(req.body)
  res.fetch('success') || raise('Could not auth track')

  result = res.fetch('result')
  status = result.fetch('status')
  challenge = result.fetch('challenge')
  _password_salt = result.fetch('password_salt')

  status != 'granted' && raise("Unauthorized track : status=#{status}")
  challenge
end

def gen_password(token, challenge)
  OpenSSL::HMAC.hexdigest('sha1', token, challenge)
end

def login(http, password)
  req = post_json(
    get_uri('/api/v4/login/session/')
  )

  req.body = JSON(
    app_id: APP_ID,
    password: password,
  )

  res = http.request(req)
  j = JSON.parse(res.body)

  if !j.fetch('success')
    warn(j)
    raise('Login failed!')
  end

  result = j.fetch('result')
  result.fetch('session_token')
end

def get_call_logs(http, session_token)
  req = Net::HTTP::Get.new(get_uri('/api/v4/call/log/'))
  req.add_field('X-Fbx-App-Auth', session_token)
  req.add_field('Content-Type', 'application/json; charset=utf-8')
  res = http.request(req)
  j = JSON.parse(res.body)

  j.fetch('success') || raise('Failed getting call log')

  j.fetch('result')
end

track_id = load_env('TRACK_ID')
app_token = load_env('APP_TOKEN')

http = Net::HTTP.new(HOST, 443)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_NONE

[track_id, app_token].any?(&:nil?) && request_auth(http)

challenge = auth_track(http, track_id)

session_token = login(http, gen_password(app_token, challenge))

calls = get_call_logs(http, session_token)

if !options.fetch(:all)
  calls = calls.select { |r| Time.at(r.fetch('datetime')).to_date == Date.today }
end

max_size = options.fetch(:max_size)

batch = if max_size
          calls.first(max_size)
        else
          calls
        end

if (re = options[:regex])
  batch = batch.select { |r| r.fetch('name').match(re) }
  if batch.empty?
    warn('No match, exiting')
    exit 0
  end
end

if (re = options[:neregex])
  batch = batch.reject { |r| r.fetch('name').match(re) }
end

if batch.empty?
  warn('Nothing to display, exiting')
  exit 0
end

batch.reduce(0) do |sum, r|
  sum += if r.fetch('type') == 'missed'
           0
         else
           r.fetch('duration')
         end
  r['total_duration'] = sum
end
longuest = ->(param) { batch.max_by { |c| c.fetch(param).length }.fetch(param) }
longuest_number = pretty_print_number(longuest.call('number'))
longuest_name = longuest.call('name')
longuest_type = longuest.call('type')

MAX_DURATION_LEN = '99d 23h 59m 59s'.length
lines = batch.map do |r|
  sprintf(
    "  %.16s  |  %-#{longuest_name.length}s  |  %-#{longuest_number.length}s  |  %-#{longuest_type.length}s  |  %s  |  %s\n",
    Time.at(r.fetch('datetime')),
    r.fetch('name'),
    pretty_print_number(r.fetch('number')),
    r.fetch('type'),
    humanize(r.fetch('duration')).rjust(MAX_DURATION_LEN),
    humanize(r.fetch('total_duration')).rjust(MAX_DURATION_LEN),
  )
end

printf(
  "  %-16s  |  %-#{longuest_name.length}s  |  %-#{longuest_number.length}s  |  %-#{longuest_type.length}s  |  %s | %s\n",
  'TIMESTAMP',
  'NAME',
  'NUMBER',
  'TYPE',
  'DURATION'.rjust(MAX_DURATION_LEN),
  'TOTAL'.rjust(MAX_DURATION_LEN),
)

longuest_line = lines.max_by(&:length)
puts '-' * (longuest_line.length - 1)

puts lines
